config/routes.rb
Rails.application.routes.draw do

	resources :pga_tour_years

	resources :players do
		member do
			post "getPlayerInfo"
			get "searchPlayerNames"
		end
	end

	resources :records

	get 'pages/index'
	root 'pages#index'

	match '*', via: :all, to: 'pages#index'

end

app/models/pga_tour_year.rb
class PgaTourYear < ActiveRecord::Base

	has_and_belongs_to_many :players

end

app/models/player.rb
class Player < ActiveRecord::Base

	has_and_belongs_to_many :pga_tour_years

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/controllers/pga_tour_years_controller.rb
class PgaTourYearsController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def index
		# page with all the data:  http://www.pgatour.com/data/players/32102/
#		@players = Player.all.first(100)
		@players = []
	end


	def getPlayerInfo
		pid = params[:player_id]

		response = {}
		content  = {}
		status   = ""
		message  = ""

		begin
			require 'net/http'
			require 'json'

			@player = Player.find(pid)

			ppid = "%05d" % pid.to_i

			career_info = {}
			bio_info = {}

	 		logger.debug "Attempting to retrieve information for player id #{ppid}..."

			begin
				uri_career  = URI("http://www.pgatour.com/data/players/#{ppid}/career.json")
				res_career = Net::HTTP.get_response(uri_career)
				if res_career.code == "200"
					career_info = JSON.parse(res_career.body)
			 		logger.debug "Found career JSON for player id #{ppid}"
				else
					raise "error code #{res_career.code}"
				end
			rescue => c_err
				career_info['error_occurred'] = true
				career_info['error_message'] = c_err.message
				logger.debug "Error occurred retrieving career JSON data for player #{ppid}: #{c_err.message}"
			end

			begin
				uri_bio	 = URI("http://www.pgatour.com/data/players/#{ppid}/bio.json")
				res_bio = Net::HTTP.get_response(uri_bio)
				if res_bio.code == "200"
					bio_info = JSON.parse(res_bio.body)
			 		logger.debug "Found bio JSON for player id #{ppid}"
				else
					raise "error code #{res_bio.code}"
				end
			rescue => b_err
				bio_info['error_occurred'] = true
				bio_info['error_message'] = b_err.message
				logger.debug "Error occurred retrieving bio JSON data for player #{ppid}: #{b_err.message}"
			end

			player = {}
			player['career']	= career_info
			player['bio']		= bio_info
			player['name']		= "#{@player.nameF} #{@player.nameL}"
			player['player_id'] = ppid
			player['headshot']  = "http://i.pgatour.com/image/upload/t_headshots_leaderboard_l/headshots_#{ppid}.png"

			content['player']	= player

			response['status']  = "success"
			response['message'] = "Retrieved player record successfully"
			response['content'] = content
		rescue => error
			response['status']  = "failure"
			response['message'] = "Error: #{error.message}"
			response['content'] = "Error while attempting to search the player database"
		ensure
			respond_to do |format|
				format.html { render :json => response.to_json }
			end
		end
	end


	def searchPlayerNames

		nme = params[:player_name]

		response = {}
		content  = {}
		status   = ""
		message  = ""

		begin
			name_results = {}
			narray = nme.split(" ")
			if narray.size == 0
				raise "No name data received by the server for processing"
			elsif narray.size == 1
				name_results = Player.where("nameF like ? or nameL like ?", "%#{narray[0]}%", "%#{narray[0]}%").order("nameL ASC").order("nameF ASC")
			elsif narray.size == 2
				name_results = Player.where("nameF like ? and nameL like ?", "%#{narray[0]}%", "%#{narray[1]}%").order("nameL ASC").order("nameF ASC")
			elsif narray.size > 2
				name_results = Player.where("nameF like ? and nameL like ?", "%#{narray[0..narray.size - 2].join(" ")}%", "%#{narray[narray.size - 1]}%").order("nameL ASC").order("nameF ASC")
			else
				raise "Unspecified error while handling name data - please refresh the page and try again"
			end

			content['players'] = name_results

			response['status'] = "success"
			response['message'] = "Retrieved #{name_results.size} records"
			response['content'] = content
		rescue => error
			response['status'] = "failure"
			response['message'] = "Error: #{error.message}"
			response['content'] = "Error while attempting to search the player database"
		ensure
			respond_to do |format|
				format.html { render :json => response.to_json }
			end
		end

	end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController


	def index
		@records = Record.all
	end


	def create
		@record = Record.new(record_params)

		if @record.save
			render json: @record
		else
			render json: @record.errors, status: :unprocessable_entity
		end
	end


	def update
		@record = Record.find(params[:id])
		if @record.update(record_params)
			render json: @record
		else
			render json: @record.errors, status: :unprocessable_entity
		end
	end


	def destroy
		@record = Record.find(params[:id])
		@record.destroy
		head :no_content
	end


	private

		def record_params
			params.require(:record).permit(:title, :amount, :date)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pga_tour_years_helper.rb
module PgaTourYearsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ReactSite</title>
	<meta name="viewport" content="initial-scale=1, maximum-scale=1">
	<%= favicon_link_tag %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato">
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
						data-toggle="collapse"
						data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a style="width:200px;padding:0px;height:60px;line-height:60px;" class="navbar-brand navlink" href="<%= root_url %>">ReactSite</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="" id="">
						<a class="navlink" href="<%= records_path %>" style="float:left;">Records</a>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>

	<div id="mainwrapper" class="container" style="margin-bottom:125px;padding:20px;box-shadow:0px 0px 20px -10px;background-color:#FFF;">
		<% if notice %>
			<p class="alert alert-success" style="">
				<%= notice %>
				<button class="notice-close btn btn-default" onclick="closeNotice(this)">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
			</p>
		<% end %>
		<% if alert %>
			<p class="alert alert-danger" style="">
				<%= alert %>
				<button class="notice-close btn btn-default" onclick="closeNotice(this)">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
			</p>
		<% end %>
		<%= yield %>
	</div>

	<footer class="footer">
		<div class="" style="padding-right:10px;padding-left:10px;">
			<p class="text-muted" style="line-height:30px;float:left;margin-bottom:0px;">ReactSite Testing</p>
			<p class="text-muted" style="line-height:30px;float:right;margin-bottom:0px;">
				Powered by <a href="http://rubyonrails.org/" class="wrmclr" target="_blank">Ruby on Rails</a>
			</p>
		</div>
	</footer>
</body>
</html>

app/views/players/index.html.erb
<%= javascript_include_tag "player_utils" %>

<%= react_component 'Players', { data: @players } %>

app/views/records/index.html.erb
<%= javascript_include_tag "record_utils" %>

<%= react_component 'Records', { data: @records } %>